defaults:
  taskcluster:
    rootUrl:        !env TASKCLUSTER_ROOT_URL
    credentials:
      clientId:     !env TASKCLUSTER_CLIENT_ID
      accessToken:  !env TASKLCUSTER_ACCESS_TOKEN
  
  server:
    port:           !env:number PORT
    env:            'development'
    forceSSL:       !env:flag FORCE_SSL
    trustProxy:     false
  
  monitor:
    mock:           true
    enable:         !env:bool MONITORING_ENABLE
  
  pulse:
    username:       !env PULSE_USERNAME
    password:       !env PULSE_PASSWORD
    hostname:       !env PULSE_HOSTNAME
    vhost:          !env PULSE_VHOST


production:
  server:
    env:            production
    trustProxy:     true

  monitor:
    mock:           false

test:
  monitor:
    enable:         false

  server:
    port:           12345
